// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzTlWOy-qttvrmt4ZrXYyrvmwNjTUzyCQ',
    appId: '1:942721491129:web:fd210d4cb971d7185e3b68',
    messagingSenderId: '942721491129',
    projectId: 'study-app-bd34a',
    authDomain: 'study-app-bd34a.firebaseapp.com',
    storageBucket: 'study-app-bd34a.appspot.com',
    measurementId: 'G-FCRK0TSW29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDid-oiJMcYAcugs8hM_PXKjTMlR33PAaU',
    appId: '1:942721491129:android:cb5767aae946f9575e3b68',
    messagingSenderId: '942721491129',
    projectId: 'study-app-bd34a',
    storageBucket: 'study-app-bd34a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhQoy5t-BGNYZ_a2M_PZrjjjl0uM5yUBQ',
    appId: '1:942721491129:ios:627f99302a7ea2a35e3b68',
    messagingSenderId: '942721491129',
    projectId: 'study-app-bd34a',
    storageBucket: 'study-app-bd34a.appspot.com',
    iosClientId: '942721491129-irv3rhq4ft39ukvlj1tg7c4te9pks9n0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStudyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhQoy5t-BGNYZ_a2M_PZrjjjl0uM5yUBQ',
    appId: '1:942721491129:ios:627f99302a7ea2a35e3b68',
    messagingSenderId: '942721491129',
    projectId: 'study-app-bd34a',
    storageBucket: 'study-app-bd34a.appspot.com',
    iosClientId: '942721491129-irv3rhq4ft39ukvlj1tg7c4te9pks9n0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStudyApp',
  );
}
